#@ load("@ytt:data", "data")
server:
  replicaCount: #@ data.values.vault_replicas
  ingress:
    enabled: true
    tls: true
    hostname: #@ data.values.vault_fqdn
    extraTls:
    - hosts:
        - #@ data.values.vault_fqdn
      secretName: #@ data.values.vault_fqdn + "-tls"